import { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  // title: 'About %s',
  title:{
    absolute:"title absolute About"
  },
  description: 'Generated By Irshad',
}

const about = () => {
  return (
    <>
    <div>About Route!</div>
    <Link href="/">Home</Link>
    </>
  )
}

export default about;