import { Metadata } from "next"
import './global.css';
export const metadata: Metadata = {
  title: {
    default: "NextJS 14",
    template: "%s | Custom + Predefine",
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
      <body>
        <header style={{backgroundColor:"gray", padding:"1rem"}}>Header</header>
        
        <main style={{backgroundColor:'ghostwhite', padding:"1rem", margin:"1rem"}}>{children}</main>

        <footer style={{backgroundColor:"lightblue", padding:"1rem"}}>Footer</footer>
      </body>

    </html>
  )
}
